### ISSUE TITLE
Incorrect output on Rogue Squadron N64 ROM

### ISSUE THREAD

**Issue by AnonBaiter** [AxioDL/amuse#1]
So I tried amuseconv on the Rogue Squadron ROM, and it sucessfully exported all the SNG files to MIDI format. However, the MIDI files themselves won't play at all, and they even have an incorrect length(about 10+ hours depending on the file).

Also on amuseplay, I tried that tool on said rom and this error appeared:
`[0.0570 FATAL ERROR boo::ApplicationWin32] unable to create D3D12 device
12:  - 0x0
11: raise - 0x7FFC431C8980
10: abort - 0x7FFC431C98B0
9: abort - 0x7FFC431C98B0
8: abort - 0x7FFC431C98B0
7: abort - 0x7FFC431C98B0
6: abort - 0x7FFC431C98B0
5: abort - 0x7FFC431C98B0
4: abort - 0x7FFC431C98B0
3: abort - 0x7FFC431C98B0
2: abort - 0x7FFC431C98B0
1: BaseThreadInitThunk - 0x7FFC450380E0
0: RtlUserThreadStart - 0x7FFC479FC580`

Keep in mind that I'm not using Windows 7, rather I'm using Windows 10.

**Comment by Antidote** [comment]
Looks like your drivers may be out of date or your device doesn't support D3D12 to the level boo is expecting, try running it again with --d3d11 or --gl as an argument (at the end).

**Comment by jackoalan** [comment]
Ok, there's a known issue converting data from the PC versions

Not sure about your issue converting the N64 ROM, are you using the North American release (NRSE)?

Also which graphics card are you using in your system? As it is right now, our software expects to find a card that supports Direct3D 11.0 *minimum*

**Comment by AnonBaiter** [comment]
I used both the North American release and the European release.
Oh, now that you mention "graphics card", only have the Intel(R) graphics card.

**Comment by jackoalan** [comment]
Could you please do Start > type "dxdiag" > open the DirectX diagnostics utility
Then tell me what feature levels your device supports in the "Display" tab?

![screenshot](http://fud.community.services.support.microsoft.com/fud/filedownloadhandler.ashx?fid=329d97b4-4c0a-4e74-9065-2b45838d1acf)

**Comment by AnonBaiter** [comment]
`Feature Levels: 11.0,10.1,10.0,9.3,9.2,9.1`
The full saved diagnostic log file is here in case you want to check that too.
[DxDiag.txt](https://github.com/AxioDL/amuse/files/333833/DxDiag.txt)

**Comment by jackoalan** [comment]
Ok, that actually helps out quite a lot

For some reason, it seems that Direct3D 12 can't communicate with your graphics card.

I'd try as antidote suggested by adding `--d3d11` to the end. If that works for you, I'll make it so an error condition like yours automatically used D3D11 instead

**Comment by AnonBaiter** [comment]
I tried the --d3d11 one to the end, and it worked. But the output is still incorrect.

**Comment by jackoalan** [comment]
Ok, one issue down

If you don't mind, could you take an invalid .mid file extracted from NRSE and attach it here? I'd like to compare it with a .mid from my system to see if they diverge at some point. 

Also let me know which song and group you're selecting it from

**Comment by AnonBaiter** [comment]
Here you go:
[title_SNG.zip](https://github.com/AxioDL/amuse/files/333839/title_SNG.zip)
And for the entire group:
[midifiles.zip](https://github.com/AxioDL/amuse/files/333840/midifiles.zip)

**Comment by jackoalan** [comment]
Thank you!

I'll get to investigating them when I have the opportunity

**Comment by Antidote** [comment]
Out of curiosity, could you post an MD5 hash of the NRSE ROM?

**Comment by AnonBaiter** [comment]
Sorry Antidote, but can you give me some pointers as how to post an MD5 hash?

**Comment by Antidote** [comment]
You caught me while I was editing my post, lol

Windows has a utility called certUtil that comes with it by default, to use it simply do the following:
CertUtil -hashfile <path-to-rom> MD5

This is the MD5 sum I get.
459c6591d816660a2f714d2a9d0dff1e  Star Wars - Rogue Squadron (USA).n64

**Comment by AnonBaiter** [comment]
There you go.

N64 USA version: 45 9c 65 91 d8 16 66 0a 2f 71 4d 2a 9d 0d ff 1e
N64 USA version(rev A): 18 22 ef 9f 6d a0 dd f2 b3 cc c7 1f 33 d4 a6 53
N64 EUR version: 14 88 00 7d b4 76 d3 ea db 42 db ab ea d0 88 b5
N64 EUR version(rev A): fc 21 aa 1c bf 31 e5 de a7 1e 80 48 78 c3 b5 f0

**Comment by Antidote** [comment]
So we can rule out bad data, yeah, this is definitely jack's territory I know next to nothing about midi. assigning jack, he's a bit busy at the moment, but we'll get this figured out.

**Comment by jackoalan** [comment]
Ok, would you mind testing the v1.4 release?
https://github.com/AxioDL/amuse/releases

I found a couple instances where the track end command could possibly slip by the decoder (mainly affecting Rogue Squadron PC data)

**Comment by AnonBaiter** [comment]
I'll see what I can do.

**Comment by Antidote** [comment]
Looking at the data we've determined that, for some reason, the note events are getting invalidated before they reach the file. We think it might be attributed to the multimap but we can't know for certain since it works fine on our machines, making debugging your issue that much more difficult. Despite this, we'll still work to figure out the exact cause and attempt to fix it. Jack knows a bit more on the situation and he'll likely elaborate on details that I can't.

**Comment by jackoalan** [comment]
Yea, at this point I'm utterly confused by the .mids output by your machine. If it's the multimap as Antidote mentioned, that would be a problem with your system's installed C++ runtime.

If you could attempt (re)installing the C++ runtime from MS' website, that's a potential solution:
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by AnonBaiter** [comment]
Well, maybe it's just me. I'll reinstall it then.

**Comment by jackoalan** [comment]
I'm performing some more tests on my end, just to be sure there's nothing missing in the converter. I just set up an Azure instance running a fresh copy of Windows Server 2016 Preview. The executable on the releases page works fine after I installed the 2015 C++ runtime (title_SNG.mid should be ~35KB)

![pasted image at 2016_06_28 13_00](https://cloud.githubusercontent.com/assets/505536/16435304/abf29e22-3d30-11e6-81b3-c631a1b218d0.png)

If you have access to another computer, it might be worth testing there

**Comment by AnonBaiter** [comment]
"If you have access to another computer, it might be worth testing there"
Well, unfortunately not...

**Comment by jackoalan** [comment]
Hmm, well you can also set up an Azure instance if you can't get it running on your system for whatever reason. Your machine is the only one I've encountered this issue on across several Windows machines and even on OS X and Linux.

There's no charge to set up a Windows Server 2016 Technical Preview instance to remote desktop into.

I'm closing this issue since we can't replicate on our end. Good Luck!!

**Comment by Antidote** [comment]
Jack found a potential cause and is investigating right now.

**Comment by jackoalan** [comment]
Ok, I found an issue with handling note-off events. It's very likely that your system was pulling in data that hadn't been properly prepared by Amuse, and that's actually Amuse's responsibility to prepare.

Try out v1.5 and let us know if it works.. If it does, please accept my apologies for being so quick to dismiss

**Comment by AnonBaiter** [comment]
Wait... Now I know what's the problem, the amuse tool won't work with the second version of the Rogue Squadron N64 ROM (labeled (Rev A) on my No-Intro N64 set), so if I try that with the first version of the same N64 game, it produces an correct output.

**Comment by Antidote** [comment]
Well, that's progress, I'm able to confirm that Rev A does indeed break in Amuse, and that gives us something to work with.

**Comment by AnonBaiter** [comment]
See? This is the reason why I opened this issue!
If you guys want the (Rev A) or Japan files, let me know! Otherwise, that's okay.

**Comment by jackoalan** [comment]
Yea, there's definitely a difference in the Rev A data, that's clear now. I've been busy debugging other codebases, so it might be a couple days for me to address it

No need to send any additional files, just midi samples at most in the comments please

**Comment by AnonBaiter** [comment]
Roger.

**Comment by jackoalan** [comment]
Ok! I think v1.6 fixes it

Rev A uses the exact same SNG format that appears in GameCube games. I sorta assumed the difference was in the game console. In fact, it looks like the revised format appeared on some of the later N64 titles, before the GameCube MusyX was even available.

**Comment by AnonBaiter** [comment]
That's cool.
However, you should also keep in mind that some Gamecube games also used the MusyX format beyond what you guys have(such as Paper Mario TTYD). Also, some of the Eurocom games also use the MusyX format, so I'll suggest you look for these games too.

I just wanted to say that I'm currently using v1.6, and it works fine with the (Rev A) and Japanese versions of the N64 game. Thanks!

**Comment by jackoalan** [comment]
Cool! Give your computer's memory pages my thanks for forcing me to consider the reasons for those .mids

The way it works now, there's dry-run of the decoder for the *revised* SNG format (what I thought was GCN). If a MIDI region is found that's not back-to-back with the next one, it tries the original SNG format instead. 

This is the only way I can really do it reliably, cause there's no version information and the file formats are otherwise identical. At least it seems to work with every SNG I throw at it so far. 

In any case, enjoy the .mids!

**Comment by jackoalan** [comment]
As far as other game support, it's definitely something I'd like to expand as I get my hands on more MusyX games.. I've mainly been using the Rogue Squadron series as a conformance test at this early-ish stage

**Comment by Antidote** [comment]
:confetti_ball: our first critical bug in Amuse solved!
